### ISSUE TITLE
When it's ready for Production Use?

### ISSUE THREAD

**Issue by lessmore92** [vahidkaargar/cms-api#1]
Hello, my friend.

I am one of your coding fans, and I am interested in your new repo.
As the repo name says, it shall be one of the most incredible APIs in the Opensource world.

I am impatiently waiting for the first release.
Can you tell, me when it's ready?

**Comment by vahidkaargar** [comment]
Hello dear Mojtaba,

Thank you for your attention. This api can be a starter dashboard for anyone may interested. I have some plans for fronts with Vuejs and If talented guys like you have time to contribute here it going to production phase very soon.
